name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Hub Login
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build Image
      run: docker build . --file Dockerfile --tag sarwonous/assets-browser:$(date +%s)
    - name: Push Image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/assets-browser